import bpy
from bpy.props import *
from datetime import datetime, timezone

def textBox(self, sentence, icon='NONE', line=56):
    layout = self.box().column()
    if sentence.startswith('LINK:'):
        url, name = sentence.split('|')
        url = url.split('LINK:', maxsplit=1)[1]
        name = name.split('NAME:', maxsplit=1)[1]
        layout.row().operator('wm.url_open', text=name, icon='URL').url = url
        return None
    sentence = sentence.split(' ')
    mix = sentence.pop(0)
    if sentence == []:
        layout.row().label(text=mix, icon=icon)
        return None
    broken = False
    while True:
        add = ' ' + sentence[0]
        if len(mix + add) < line:
            mix += add
            sentence.pop(0)
            if sentence == []:
                layout.row().label(text=mix, icon='NONE' if broken else icon)
                return None

        else:
            layout.row().label(text=mix, icon='NONE' if broken else icon)
            broken = True
            mix = sentence[0]
            sentence.pop(0)
            if sentence == []:
                layout.row().label(text=mix)
                return None

class generictext(bpy.types.Operator):
    text: StringProperty(default='')
    icons: StringProperty()
    size: StringProperty()
    width: IntProperty(default=400)
    url: StringProperty(default='')

def format_time(timestamp):
    # This logic was generated by ChatGPT
    date = datetime.strptime(timestamp, "%Y-%m-%dT%H:%M:%SZ")
    date = date.replace(tzinfo=timezone.utc)
    return date.timestamp()